const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.CONCILIA_CONFIG||{}; let selected=[], rows=[], currentUser=null;
async function loadUsers(){const sel=$('#user');sel.disabled=true;sel.innerHTML='<option value="">Cargando usuarios...</option>';try{const r=await fetch(`${cfg.AUTH_URL}?accion=usuarios&_=${Date.now()}`);const d=await r.json();if(d.error===true)throw Error(d.mensaje||'No fue posible obtener los usuarios');const users=Array.isArray(d.usuarios)?d.usuarios:Array.isArray(d.data)?d.data:[];sel.innerHTML='<option value="">Selecciona tu usuario</option>'+users.map(u=>{const usuario=String(u.usuario||u.user||'').trim();const nombre=String(u.nombre||u.name||usuario).trim();return usuario?`<option value="${usuario.replace(/"/g,'&quot;')}">${nombre}</option>`:''}).join('');if(!users.length)sel.innerHTML='<option value="">No hay usuarios activos</option>';}catch(e){sel.innerHTML='<option value="">No se pudieron cargar los usuarios</option>';$('#loginMsg').textContent='No pude cargar la lista de usuarios: '+e.message;}finally{sel.disabled=false;}}
const fmt=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n||0);
const normId=s=>String(s||'').replace(/\D/g,'').replace(/^0+/,'')||'0';
function csvLine(line){let a=[],v='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){a.push(v);v=''}else v+=c}a.push(v);return a}
function parseCSV(t){return t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()).map(csvLine)}
function num(v){let x=parseFloat(String(v||'').replace(/,/g,''));return Number.isFinite(x)?x:0}
function brandFrom(name,text){let n=(name+' '+text.slice(0,500)).toUpperCase();if(n.includes('TRT'))return'TRT';if(n.includes('SUR')||n.includes('AAO'))return'SUR';if(n.includes('ADO'))return'ADO';return'OTRO'}
async function login(){let u=$('#user').value.trim(),p=$('#pass').value;if(!u||!p)return $('#loginMsg').textContent='Escribe usuario y contraseña.';$('#loginMsg').textContent='Validando...';try{let url=`${cfg.AUTH_URL}?accion=login&usuario=${encodeURIComponent(u)}&password=${encodeURIComponent(p)}`;let r=await fetch(url),d=await r.json();let ok=d.ok===true||d.success===true||d.error===false||d.acceso===true;if(!ok)throw Error(d.mensaje||'Credenciales incorrectas');currentUser={usuario:u,nombre:d.nombre||d.name||u,rango:d.rango||d.rol||''};openApp()}catch(e){$('#loginMsg').textContent='No pude validar el acceso: '+e.message}}
function openApp(){localStorage.setItem('conciliiaUser',JSON.stringify(currentUser));$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#hello').textContent=`👋 Hola ${currentUser.nombre}.`;$('#who').textContent=currentUser.rango?`${currentUser.nombre} · ${currentUser.rango}`:currentUser.nombre}
$('#loginBtn').onclick=login;
loadUsers();$('#pass').addEventListener('keydown',e=>e.key==='Enter'&&login());$('#logout').onclick=()=>{localStorage.removeItem('conciliiaUser');location.reload()};
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active')});
$('#files').onchange=e=>{selected=[...e.target.files];$('#fileList').innerHTML=selected.map(f=>`<div>✓ ${f.name}</div>`).join('')};
async function reconcile(){if(!selected.length)return setStatus('🤔 Todavía me faltan los archivos JDE y Saldos por Conductor para comenzar.');let files=[];for(const f of selected)files.push({name:f.name,text:await f.text()});let jde={},sal={},found={};for(const f of files){let data=parseCSV(f.text),b=brandFrom(f.name,f.text);if(b==='OTRO')continue;found[b]=found[b]||{jde:false,sal:false};let isJ=/^TIPO LM AUX/i.test((data[0]||[])[0]||'')||f.name.toUpperCase().includes('JDE');if(isJ){found[b].jde=true;let h=data[0].map(x=>x.trim()),idI=h.findIndex(x=>x.toLowerCase()==='lm aux'),nameI=h.findIndex(x=>x.toLowerCase().includes('descripción lm')),balI=h.findIndex(x=>x.toLowerCase().includes('importe real acumulado'));for(const r of data.slice(1)){let id=normId(r[idI]);if(id==='0')continue;jde[b+'|'+id]={brand:b,id,name:(r[nameI]||'').trim(),amount:num(r[balI])}}}else{found[b].sal=true;for(const r of data.slice(2)){if(!r[0]||/^total por empleado/i.test(r[0])||!/^[0-9]+$/.test(r[0].trim()))continue;let id=normId(r[0]),k=b+'|'+id;if(!sal[k])sal[k]={brand:b,id,name:[r[1],r[2],r[3]].filter(Boolean).join(' ').trim(),amount:0};sal[k].amount+=num(r[9])}}}
let keys=new Set([...Object.keys(jde),...Object.keys(sal)]);rows=[...keys].map(k=>{let j=jde[k],s=sal[k],a=j?.amount||0,b=s?.amount||0,d=a-b;let state=!j?'Solo en Saldos':!s?'Solo en JDE':Math.abs(d)<=.01?'Cuadrado':'Diferencia de saldo';return{brand:(j||s).brand,id:(j||s).id,name:j?.name||s?.name||'',jde:a,saldos:b,diff:d,state}}).sort((a,b)=>Math.abs(b.diff)-Math.abs(a.diff));render();let missing=[];for(const b of ['ADO','SUR','TRT']){if(!found[b]?.jde)missing.push(`JDE ${b}`);if(!found[b]?.sal)missing.push(`Saldos ${b}`)}if(missing.length)setStatus('🤔 Pude conciliar parcialmente, pero todavía me falta: '+missing.join(', ')+'.');else setStatus(`🎉 ¡Excelente trabajo!\nLa conciliación terminó. Encontré ${rows.filter(r=>r.state!=='Cuadrado').length} registros con diferencia para revisar.`);show('resumen')}
$('#run').onclick=reconcile;function setStatus(t){$('#status').textContent=t}function show(id){document.querySelector(`nav button[data-view="${id}"]`).click()}
function render(){let dif=rows.filter(r=>r.state!=='Cuadrado');$('#kConductores').textContent=rows.length;$('#kDif').textContent=dif.length;$('#kAdeudo').textContent=fmt(rows.reduce((s,r)=>s+r.saldos,0));$('#kNeta').textContent=fmt(rows.reduce((s,r)=>s+r.diff,0));$('#brandCards').innerHTML=['ADO','SUR','TRT'].map(b=>{let x=rows.filter(r=>r.brand===b),d=x.filter(r=>r.state!=='Cuadrado');return `<div class="brand-card"><b>${b}</b><h2>${d.length} diferencias</h2><small>${x.length} conductores · Saldos ${fmt(x.reduce((s,r)=>s+r.saldos,0))}</small></div>`}).join('');renderTable();let debts=rows.filter(r=>r.saldos>0).sort((a,b)=>b.saldos-a.saldos).slice(0,20);$('#debtList').innerHTML=debts.map((r,i)=>`<div class="debt"><div class="rank">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div><b>${r.name}</b><br><small>${r.brand} · ${r.id}</small></div><strong>${fmt(r.saldos)}</strong></div>`).join('')}
function renderTable(){let q=$('#search').value.toLowerCase(),br=$('#brand').value,ty=$('#type').value;let f=rows.filter(r=>(!q||(r.id+' '+r.name+' '+r.brand).toLowerCase().includes(q))&&(!br||r.brand===br)&&(!ty||r.state===ty));$('#diffBody').innerHTML=f.map(r=>`<tr><td>${r.brand}</td><td>${r.id}</td><td>${r.name}</td><td class="money">${fmt(r.jde)}</td><td class="money">${fmt(r.saldos)}</td><td class="money">${fmt(r.diff)}</td><td><span class="badge ${r.state==='Cuadrado'?'ok':r.state.includes('Solo')?'warn':'bad'}">${r.state}</span></td></tr>`).join('')}
['search','brand','type'].forEach(id=>$('#'+id).addEventListener('input',renderTable));$('#export').onclick=()=>{let h=['Marca','Conductor','Nombre','JDE','Saldos','Diferencia','Estado'],csv=[h,...rows.map(r=>[r.brand,r.id,r.name,r.jde,r.saldos,r.diff,r.state])].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download='CONCILIA_JDE_vs_SALDOS.csv';a.click()};
function answer(q){q=q.toLowerCase();if(!rows.length)return 'Primero necesito que cargues y concilies los archivos.';if(q.includes('cuánt')||q.includes('diferencia'))return `Encontré ${rows.filter(r=>r.state!=='Cuadrado').length} registros con diferencia de ${rows.length} conductores analizados.`;if(q.includes('mayor')||q.includes('adeudo')){let r=[...rows].sort((a,b)=>b.saldos-a.saldos)[0];return `El mayor adeudo en Saldos es ${fmt(r.saldos)} y corresponde a ${r.name} (${r.brand}, conductor ${r.id}).`};if(q.includes('falta')||q.includes('archivo'))return 'La conciliación completa requiere 6 archivos: JDE ADO, JDE SUR, JDE TRT y sus tres reportes de Saldos por Conductor.';return 'Puedo ayudarte a interpretar diferencias, adeudos y registros que aparecen solo en uno de los dos sistemas.'}
function ask(q){if(!q)return;$('#chatLog').insertAdjacentHTML('beforeend',`<div class="me">${q}</div><div class="bot">🤖 ${answer(q)}</div>`);$('#question').value=''}$('#ask').onclick=()=>ask($('#question').value);$('#question').addEventListener('keydown',e=>e.key==='Enter'&&ask(e.target.value));$$('.suggestions button').forEach(b=>b.onclick=()=>ask(b.textContent));
let saved=localStorage.getItem('conciliiaUser');if(saved){try{currentUser=JSON.parse(saved);openApp()}catch{}}
